[project]
name = 'citycoins-protocol'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SP000000000000000000002Q6VF78.pox'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.citycoin-core-v2-trait'

[[project.requirements]]
contract_id = 'SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.citycoin-vrf-v2'

[[project.requirements]]
contract_id = 'SP1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8Y634C7R.miamicoin-auth-v2'

[[project.requirements]]
contract_id = 'SP1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8Y634C7R.miamicoin-core-v2'

[[project.requirements]]
contract_id = 'SP1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8Y634C7R.miamicoin-token-v2'

[[project.requirements]]
contract_id = 'SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.newyorkcitycoin-auth-v2'

[[project.requirements]]
contract_id = 'SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.newyorkcitycoin-core-v2'

[[project.requirements]]
contract_id = 'SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.newyorkcitycoin-token-v2'

[[project.requirements]]
contract_id = 'ST000000000000000000002AMW42H.pox'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.nft-trait'

[[project.requirements]]
contract_id = 'ST1XQXW9JNQ1W4A7PYTN3HCHPEY7SHM6KPA085ES6.citycoin-core-v2-trait'

[[project.requirements]]
contract_id = 'ST1XQXW9JNQ1W4A7PYTN3HCHPEY7SHM6KPA085ES6.citycoin-vrf-v2'

[[project.requirements]]
contract_id = 'ST1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8WRH7C6H.miamicoin-auth-v2'

[[project.requirements]]
contract_id = 'ST1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8WRH7C6H.miamicoin-core-v2'

[[project.requirements]]
contract_id = 'ST1H1733V5MZ3SZ9XRW9FKYGEZT0JDGEB8WRH7C6H.miamicoin-token-v2'

[[project.requirements]]
contract_id = 'STSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1D64KKHQ.newyorkcitycoin-auth-v2'

[[project.requirements]]
contract_id = 'STSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1D64KKHQ.newyorkcitycoin-core-v2'

[[project.requirements]]
contract_id = 'STSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1D64KKHQ.newyorkcitycoin-token-v2'
[contracts.base-dao]
path = 'contracts/base-dao.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd001-direct-execute]
path = 'contracts/extensions/ccd001-direct-execute.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd002-trait]
path = 'contracts/traits/ccd002-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd002-treasury-mia-mining]
path = 'contracts/extensions/ccd002-treasury.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd002-treasury-mia-stacking]
path = 'contracts/extensions/ccd002-treasury.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd002-treasury-nyc-mining]
path = 'contracts/extensions/ccd002-treasury.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd002-treasury-nyc-stacking]
path = 'contracts/extensions/ccd002-treasury.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd003-user-registry]
path = 'contracts/extensions/ccd003-user-registry.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd004-city-registry]
path = 'contracts/extensions/ccd004-city-registry.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd005-city-data]
path = 'contracts/extensions/ccd005-city-data.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd006-citycoin-mining]
path = 'contracts/extensions/ccd006-citycoin-mining.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd006-trait]
path = 'contracts/traits/ccd006-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd007-citycoin-stacking]
path = 'contracts/extensions/ccd007-citycoin-stacking.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd007-trait]
path = 'contracts/traits/ccd007-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd008-city-activation]
path = 'contracts/extensions/ccd008-city-activation.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd009-auth-v2-adapter]
path = 'contracts/extensions/ccd009-auth-v2-adapter.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd010-core-v2-adapter]
path = 'contracts/extensions/ccd010-core-v2-adapter.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccd011-stacking-payouts]
path = 'contracts/extensions/ccd011-stacking-payouts.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccip012-bootstrap]
path = 'contracts/proposals/ccip012-bootstrap.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccip013-activation]
path = 'contracts/proposals/ccip013-activation.clar'
clarity_version = 1
epoch = 2.0

[contracts.ccip013-migration]
path = 'contracts/proposals/ccip013-migration.clar'
clarity_version = 1
epoch = 2.0

[contracts.citycoin-core-v2-trait]
path = 'contracts/legacy/citycoin-core-v2-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.citycoin-token-v2-trait]
path = 'contracts/legacy/citycoin-token-v2-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.citycoin-vrf-v2]
path = 'tests/contracts/external/citycoin-vrf-v2.clar'
clarity_version = 1
epoch = 2.0

[contracts.crypto-twins]
path = 'contracts/crypto-twins.clar'
clarity_version = 1
epoch = 2.0

[contracts.extension-trait]
path = 'contracts/traits/extension-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.miamicoin-auth-v2]
path = 'contracts/legacy/miamicoin-auth-v2.clar'
clarity_version = 1
epoch = 2.0

[contracts.miamicoin-core-v2]
path = 'contracts/legacy/miamicoin-core-v2.clar'
clarity_version = 1
epoch = 2.0

[contracts.miamicoin-token-v2]
path = 'contracts/legacy/miamicoin-token-v2.clar'
clarity_version = 1
epoch = 2.0

[contracts.newyorkcitycoin-auth-v2]
path = 'contracts/legacy/newyorkcitycoin-auth-v2.clar'
clarity_version = 1
epoch = 2.0

[contracts.newyorkcitycoin-core-v2]
path = 'contracts/legacy/newyorkcitycoin-core-v2.clar'
clarity_version = 1
epoch = 2.0

[contracts.newyorkcitycoin-token-v2]
path = 'contracts/legacy/newyorkcitycoin-token-v2.clar'
clarity_version = 1
epoch = 2.0

[contracts.proposal-trait]
path = 'contracts/traits/proposal-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip-09]
path = 'contracts/sip-09.clar'
clarity_version = 1
epoch = 2.0

[contracts.stacking-trait]
path = 'contracts/traits/stacking-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd001-direct-execute-001]
path = 'tests/contracts/proposals/test-ccd001-direct-execute-001.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd001-direct-execute-002]
path = 'tests/contracts/proposals/test-ccd001-direct-execute-002.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd001-direct-execute-003]
path = 'tests/contracts/proposals/test-ccd001-direct-execute-003.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-001]
path = 'tests/contracts/proposals/test-ccd002-treasury-001.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-002]
path = 'tests/contracts/proposals/test-ccd002-treasury-002.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-003]
path = 'tests/contracts/proposals/test-ccd002-treasury-003.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-004]
path = 'tests/contracts/proposals/test-ccd002-treasury-004.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-005]
path = 'tests/contracts/proposals/test-ccd002-treasury-005.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-006]
path = 'tests/contracts/proposals/test-ccd002-treasury-006.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-007]
path = 'tests/contracts/proposals/test-ccd002-treasury-007.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-008]
path = 'tests/contracts/proposals/test-ccd002-treasury-008.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-009]
path = 'tests/contracts/proposals/test-ccd002-treasury-009.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-010]
path = 'tests/contracts/proposals/test-ccd002-treasury-010.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-011]
path = 'tests/contracts/proposals/test-ccd002-treasury-011.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd002-treasury-012]
path = 'tests/contracts/proposals/test-ccd002-treasury-012.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd003-user-registry-001]
path = 'tests/contracts/proposals/test-ccd003-user-registry-001.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd003-user-registry-002]
path = 'tests/contracts/proposals/test-ccd003-user-registry-002.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd003-user-registry-003]
path = 'tests/contracts/proposals/test-ccd003-user-registry-003.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd004-city-registry-001]
path = 'tests/contracts/proposals/test-ccd004-city-registry-001.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd004-city-registry-002]
path = 'tests/contracts/proposals/test-ccd004-city-registry-002.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-001]
path = 'tests/contracts/proposals/test-ccd005-city-data-001.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-002]
path = 'tests/contracts/proposals/test-ccd005-city-data-002.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-003]
path = 'tests/contracts/proposals/test-ccd005-city-data-003.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-004]
path = 'tests/contracts/proposals/test-ccd005-city-data-004.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-005]
path = 'tests/contracts/proposals/test-ccd005-city-data-005.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-006]
path = 'tests/contracts/proposals/test-ccd005-city-data-006.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-007]
path = 'tests/contracts/proposals/test-ccd005-city-data-007.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-008]
path = 'tests/contracts/proposals/test-ccd005-city-data-008.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-009]
path = 'tests/contracts/proposals/test-ccd005-city-data-009.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-010]
path = 'tests/contracts/proposals/test-ccd005-city-data-010.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-011]
path = 'tests/contracts/proposals/test-ccd005-city-data-011.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-012]
path = 'tests/contracts/proposals/test-ccd005-city-data-012.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-013]
path = 'tests/contracts/proposals/test-ccd005-city-data-013.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-014]
path = 'tests/contracts/proposals/test-ccd005-city-data-014.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-015]
path = 'tests/contracts/proposals/test-ccd005-city-data-015.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-016]
path = 'tests/contracts/proposals/test-ccd005-city-data-016.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-017]
path = 'tests/contracts/proposals/test-ccd005-city-data-017.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-018]
path = 'tests/contracts/proposals/test-ccd005-city-data-018.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd005-city-data-019]
path = 'tests/contracts/proposals/test-ccd005-city-data-019.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd006-citycoin-mining-001]
path = 'tests/contracts/proposals/test-ccd006-citycoin-mining-001.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd006-citycoin-mining-002]
path = 'tests/contracts/proposals/test-ccd006-citycoin-mining-002.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd006-citycoin-mining-003]
path = 'tests/contracts/proposals/test-ccd006-citycoin-mining-003.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd006-citycoin-mining-004]
path = 'tests/contracts/proposals/test-ccd006-citycoin-mining-004.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd006-citycoin-mining-005]
path = 'tests/contracts/proposals/test-ccd006-citycoin-mining-005.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-001]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-001.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-002]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-002.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-003]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-003.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-004]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-004.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-005]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-005.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-006]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-006.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-007]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-007.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-008]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-008.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-009]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-009.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-010]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-010.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-011]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-011.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd007-citycoin-stacking-012]
path = 'tests/contracts/proposals/test-ccd007-citycoin-stacking-012.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccd011-stacking-payouts-001]
path = 'tests/contracts/proposals/test-ccd011-stacking-payouts-001.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccext-governance-token-mia]
path = 'tests/contracts/external/test-ccext-governance-token-mia.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccext-governance-token-nyc]
path = 'tests/contracts/external/test-ccext-governance-token-nyc.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccext-nft-mia]
path = 'tests/contracts/external/test-ccext-nft-mia.clar'
clarity_version = 1
epoch = 2.0

[contracts.test-ccext-nft-nyc]
path = 'tests/contracts/external/test-ccext-nft-nyc.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = true
