[project]
name = 'citycoins-protocol'
description = ''
authors = []
telemetry = false
cache_dir = '.cache'

[[project.requirements]]
contract_id = 'SPSCWDV3RKV5ZRN1FQD84YE1NQFEDJ9R1F4DYQ11.citycoin-vrf-v2'

[contracts.base-dao]
path = 'contracts/base-dao.clar'
clarity_version = 1

[contracts.ccd001-direct-execute]
path = 'contracts/extensions/ccd001-direct-execute.clar'
clarity_version = 1

[contracts.ccd002-treasury]
path = 'contracts/extensions/ccd002-treasury.clar'
clarity_version = 1

[contracts.ccd003-user-registry]
path = 'contracts/extensions/ccd003-user-registry.clar'
clarity_version = 1

[contracts.ccd004-city-registry]
path = 'contracts/extensions/ccd004-city-registry.clar'
clarity_version = 1

[contracts.ccd005-city-mining]
path = 'contracts/extensions/ccd005-city-mining.clar'
clarity_version = 1

[contracts.ccd006-city-stacking]
path = 'contracts/extensions/ccd006-city-stacking.clar'
clarity_version = 1

[contracts.ccip-test-proposal-001]
path = 'contracts/proposals/ccip-test-proposal-001.clar'
clarity_version = 1

[contracts.ccip012-bootstrap]
path = 'contracts/proposals/ccip012-bootstrap.clar'
clarity_version = 1

[contracts.extension-trait]
path = 'contracts/traits/extension-trait.clar'
clarity_version = 1

[contracts.proposal-trait]
path = 'contracts/traits/proposal-trait.clar'
clarity_version = 1

[contracts.sip009-nft-trait]
path = 'contracts/traits/sip009-nft-trait.clar'
clarity_version = 1

[contracts.sip010-ft-trait]
path = 'contracts/traits/sip010-ft-trait.clar'
clarity_version = 1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
