[project]
name = "protocol"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

# Base DAO

[contracts.base-dao]
path = "contracts/base-dao.clar"

# Extensions

[contracts.ccd001-direct-execute]
path = "contracts/extensions/ccd001-direct-execute.clar"

[contracts.ccd002-treasury-mia]
path = "contracts/extensions/ccd002-treasury-mia.clar"

[contracts.ccd002-treasury-nyc]
path = "contracts/extensions/ccd002-treasury-nyc.clar"

# DAO Traits

[contracts.extension-trait]
path = "contracts/traits/extension-trait.clar"
depends_on = []

[contracts.proposal-trait]
path = "contracts/traits/proposal-trait.clar"
depends_on = []

# Stacks Traits

[contracts.sip009-nft-trait]
path = "contracts/traits/sip009-nft-trait.clar"
depends_on =  []

[contracts.sip010-ft-trait]
path = "contracts/traits/sip010-ft-trait.clar"
depends_on =  []

# REPL settings

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
